name: Build Android Auto APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4

    - name: Configurar Java JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Conceder permissão ao Gradle
      run: chmod +x ./gradlew

    - name: Compilar com Gradle (Ignorar Avisos)
      run: ./gradlew assembleDebug -Xlint:-deprecation -Xlint:-unchecked

    - name: Upload do APK Gerado
      uses: actions/upload-artifact@v4
      with:
        name: android-auto-apk
        path: app/build/outputs/apk/debug/app-debug.apk
